sudo: false
language: go
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  on:
    branch: master
  local_dir: public
  repo: dashjay/dashjay.github.io
  target_branch: master
  email: dashjay@aliyun.com
  name: dashjay
