dist: xenial
language: python
python: 3.7

before_install:
  - sudo apt-get update -qq

install:
  # install latest hugo release version
  - wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email dashjay@aliyun.com
  - git config --global user.name dashjay

script:
  - hugo -d ./dist/

after_success:
  - DATE=$(date)
  - cd dist
  - git init
  - git remote add origin https://dashjay:${password}@github.com/dashjay/dashjay.github.io
  - git add .
  - git commit -m "${DATE}"
  - git push origin master -f
