baseurl = "/"
languageCode = "en-us"
title = "Dashjay's"
theme = "hugo-lithium"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "LearnCPP"
    url = "/learncpp"
    weight = 5

[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 10

[[menu.main]]
    name = "日报"
    url = "/daily"
    weight = 20

[[menu.main]]
    name = "Intro"
    url = "/intro"
    weight = 30

[[menu.main]]
    name = "SuperLcx"    
    weight = 60
    url = "/superlcx.CN"

[params]
    highlightjsTheme = "prism"
    highlightjsVersion = "10.1.2"
    custom_css = ["css/theme-override.css"]

[markup]
  defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2    
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = false
        noClasses = true
        style = "dracula"
        tabWidth = 4

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
