baseurl = "/"
languageCode = "en-us"
title = "Dashjay's"
theme = "hugo-lithium-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "LearnCPP"
    url = "/learncpp"
    weight = 5

[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 10

[[menu.main]]
    name = "日报"
    url = "/daily"
    weight = 20

[[menu.main]]
    name = "Intro"
    url = "/intro"
    weight = 30

[[menu.main]]
    name = "EN"
    url = "/EN"
    weight = 40
    
[[menu.main]]
    name = "RSS"    
    weight = 60
    url = "/index.xml"

[params]
    custom_css = ["css/theme-override.css"]
