name: Push

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: install hugo 
        run: go install github.com/gohugoio/hugo@latest

      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: git config --global user.email dashjay@aliyun.com
      - run: git config --global init.defaultBranch master
      - run: git config --global user.name dashjay
      - run: hugo -d ./dist/
      - run: cd dist && git init & git add -A && git commit -m $(date)
      - run: git remote add origin https://dashjay:${PASSWORD}/dashjay/dashjay.github.io.git
      - run: git push

