name: Push

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: install hugo 
        run: CGO_ENABLED=1 go install --tags extended github.com/gohugoio/hugo@latest

      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: git config --global user.email dashjay@aliyun.com
      - run: git config --global init.defaultBranch master
      - run: git config --global user.name dashjay
      - run: hugo -d ./dist/

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './dist'
          destination-github-username: 'dashjay'
          destination-repository-name: 'dashjay.github.io'
          user-email: dashjay@aliyun.com
          target-branch: master